name: bert
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.12.1=h00a0c3c_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - audioread=3.0.1=py310h5588dad_3
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310h540bb41_1
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he9e932c_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - click=8.2.1=py310haa95532_1
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py310h214f63a_0
  - cuda-cccl=13.1.115=h415d894_0
  - cuda-cccl_win-64=13.1.115=hc667259_0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.1.115=hd7d98ca_0
  - cuda-opencl-dev=13.1.115=hd7d98ca_0
  - cuda-profiler-api=13.1.115=h415d894_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.1=hd92462c_3
  - cycler=0.12.1=py310haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.20=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.3=py310haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py310h02ab6af_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=hfbffc0b_0
  - fribidi=1.0.16=haf45083_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py310h8598115_0
  - graphite2=1.3.14=hd77b12b_1
  - h5py=3.15.1=nompi_py310hb7e4da9_101
  - harfbuzz=12.3.0=h3ef6528_1
  - hdf5=1.14.6=nompi_h89f0904_105
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310haa95532_0
  - joblib=1.5.3=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - kiwisolver=1.4.9=py310h03f52e7_0
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libaec=1.1.5=haf901d7_0
  - libavif=1.3.0=h5bd13ec_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.1.81=hd7d98ca_0
  - libcurand-dev=10.4.1.81=hd7d98ca_0
  - libcurl=8.18.0=h43ecb02_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libflac=1.5.0=h08124e9_1
  - libglib=2.86.3=h9bccc14_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.22.1=hb237eb7_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libogg=1.3.5=h2466b09_1
  - libopenjpeg=2.5.4=h02ab6af_1
  - libopus=1.6.1=h6a83c73_0
  - libpng=1.6.54=ha15c746_0
  - libpq=17.6=h64815fc_1
  - librosa=0.11.0=pyhd8ed1ab_0
  - libsndfile=1.2.2=hc3b4fa0_2
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h3a18249_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.6.0=h55ef9bb_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - llvmlite=0.46.0=py310hfe4b161_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib=3.10.8=py310haa95532_0
  - matplotlib-base=3.10.8=py310h26e45b9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpg123=1.32.9=h01009b0_0
  - mpmath=1.3.0=py310haa95532_0
  - msgpack-python=1.1.2=py310he9f1925_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=py310haa95532_0
  - nltk=3.9.2=py310ha55a155_0
  - numba=0.63.1=py310h04bad52_0
  - numexpr=2.11.0=py310hdb065b2_0
  - numpy=2.2.5=py310h5f75535_0
  - numpy-base=2.2.5=py310h23d94f8_0
  - opencl-headers=2025.07.22=h885b0b7_0
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310h42c1672_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h5740b90_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.0=py310h6b7a805_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pooch=1.9.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py310h1637853_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py310haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=py310haa95532_0
  - pyqt=6.7.1=py310h378bd72_2
  - pyqt6-sip=13.9.1=py310h02ab6af_2
  - pysocks=1.7.1=py310haa95532_1
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py310haa95532_0
  - pywin32=311=py310h282bd7d_1
  - pyyaml=6.0.3=py310hb9a58be_0
  - pyzmq=27.1.0=py310h535538e_0
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - regex=2025.11.3=py310h02ab6af_0
  - requests=2.32.5=py310haa95532_1
  - scikit-learn=1.7.2=py310h7f7e138_1
  - scipy=1.15.3=py310h180bac5_0
  - seaborn=0.13.2=py310haa95532_3
  - setuptools=72.1.0=py310haa95532_0
  - sip=6.10.0=py310h5da7b33_0
  - six=1.17.0=py310haa95532_0
  - soxr=0.1.3=hcfcfb64_3
  - soxr-python=1.0.0=py310h73ae2b4_1
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - standard-aifc=3.13.0=py310h5588dad_3
  - standard-sunau=3.13.0=py310h5588dad_3
  - tbb=2021.8.0=h59b6b97_0
  - tbb-devel=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py310h4442805_1
  - tk=8.6.15=hf199647_0
  - tomli=2.4.0=py310haa95532_0
  - tornado=6.5.4=py310h02ab6af_0
  - tqdm=4.67.1=py310h4442805_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py310haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - wheel=0.46.3=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.4.0
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - alembic==1.18.3
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - cloudpickle==3.1.2
      - cryptography==46.0.4
      - databricks-sdk==0.82.0
      - datasets==4.5.0
      - dill==0.4.0
      - docker==7.1.0
      - evaluate==0.4.6
      - fastapi==0.128.0
      - flask==2.3.3
      - flask-cors==6.0.2
      - flatbuffers==25.12.19
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.48.0
      - google-pasta==0.2.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.3.1
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huey==2.6.0
      - huggingface-hub==1.3.5
      - imbalanced-learn==0.14.1
      - importlib-metadata==8.7.1
      - itsdangerous==2.2.0
      - keras==3.12.0
      - libclang==18.1.1
      - mako==1.3.10
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mlflow==3.9.0
      - mlflow-skinny==3.9.0
      - mlflow-tracing==3.9.0
      - multidict==6.7.1
      - multiprocess==0.70.18
      - namex==0.1.0
      - opencv-python==4.13.0.90
      - opentelemetry-api==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - opt-einsum==3.4.0
      - optree==0.18.0
      - prettytable==3.17.0
      - propcache==0.4.1
      - protobuf==6.33.5
      - pyarrow==22.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - rich==14.3.2
      - rsa==4.9.1
      - safetensors==0.7.0
      - shellingham==1.5.4
      - sklearn-compat==0.1.5
      - skops==0.13.0
      - smmap==5.0.2
      - sqlalchemy==2.0.46
      - sqlparse==0.5.5
      - starlette==0.50.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.3.0
      - tokenizers==0.22.2
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - transformers==5.0.0
      - typer-slim==0.21.1
      - typing-inspection==0.4.2
      - uvicorn==0.40.0
      - waitress==3.0.2
      - werkzeug==3.1.5
      - wordcloud==1.9.6
      - wrapt==2.1.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: D:\Anaconda\envs\bert
